#!/bin/bash

runCommand()
{
    sol=$(basename -- "$1")
    sol="${sol%.*}"
    if [ -f log."$sol" ]; then rm log."$sol"; fi
    "$@" 1> >(tee -a log."$sol") 2> >(tee -a log."$sol" >&2)
    err=$?
    if [ ! $err -eq 0 ]; then exit $err; fi
}

runParallel()
{
    nproc="$1"
    shift
    exe="$(which $1)"
    sol=$(basename -- "$1")
    sol="${sol%.*}"
    shift
    if [ -f log."$sol" ]; then rm log."$sol"; fi
    export OMPI_MCA_btl_vader_single_copy_mechanism=none  # Workaround for open-mpi/docker bug
    mpiexec -np $nproc "$exe" -parallel "$@" 1> >(tee -a log."$sol") 2> >(tee -a log."$sol" >&2)
    err=$?
    if [ ! $err -eq 0 ]; then exit $err; fi
}

GMSH_EXE='/home/oliver/software/gmsh-4.13.1-Linux64/bin/gmsh'
if [[ $OSTYPE == 'darwin'* ]]
then
    NTHREADS=$(sysctl -n hw.logicalcpu)
else
    NTHREADS=$(nproc)
fi
runCommand "$GMSH_EXE" -nt $NTHREADS - "gmsh/Box_Geometry.geo"

# Unset and source bashrc
FOAMDIR="/usr/lib/openfoam/openfoam2406"
if [ ! -z "$FOAMDIR" ]
then
    source "$FOAMDIR/etc/config.sh/unset" 2> /dev/null
    source "$FOAMDIR/etc/bashrc"
fi

runCommand gmshToFoam "gmsh/Box_Geometry.msh"

if [ ! -z $FOAM_API ] || [ $WM_PROJECT_VERSION -lt 9 ] 2>/dev/null
then
    runCommand transformPoints -scale "(0.001 0.001 0.001)"
else
    runCommand transformPoints "scale=(0.001 0.001 0.001)"
fi


# Extract surface mesh and convert to mm for visualisation in FreeCAD
runCommand foamToSurface -scale 1000 -tri surfaceMesh.vtk
