#!/bin/bash

runCommand()
{
    if [ "$1" == "mpirun" ]; then sol=$4; else sol=$1; fi
    if [ -f log.$sol ]; then rm log.$sol; fi
    "$@" 1> >(tee -a log.$sol) 2> >(tee -a log.$sol >&2)
    err=$?
    if [ ! $err -eq 0 ]; then exit $err; fi
}

#SOURCE#
# Create symbolic links to polyMesh.org
if [ ! -d constant/polyMesh ]; then
    mkdir constant/polyMesh
    ln -s ../polyMesh.org/boundary constant/polyMesh
    ln -s ../polyMesh.org/faces constant/polyMesh
    ln -s ../polyMesh.org/neighbour constant/polyMesh
    ln -s ../polyMesh.org/owner constant/polyMesh
    ln -s ../polyMesh.org/points constant/polyMesh
    if [ -f constant/polyMesh.org/faceZones ]; then
        ln -s ../polyMesh.org/faceZones constant/polyMesh
    fi
fi

