#!/bin/bash

runCommand()
{
    if [ "$1" == "mpiexec" ]; then sol="$4"; else sol="$1"; fi
    sol=$(basename -- "$sol")
    sol="${sol%.*}"
    if [ -f log."$sol" ]; then rm log."$sol"; fi
    "$@" 1> >(tee -a log."$sol") 2> >(tee -a log."$sol" >&2)
    err=$?
    if [ ! $err -eq 0 ]; then exit $err; fi
}

# Unset and source bashrc
FOAMDIR="/usr/lib/openfoam/openfoam2112"
if [ ! -z "$FOAMDIR" ]
then
    source "$FOAMDIR/etc/config.sh/unset" 2> /dev/null
    source "$FOAMDIR/etc/bashrc"
fi

# Copy mesh from mesh case dir if available
MESHDIR="../meshCaseDuct"
if [ -f "$MESHDIR"/constant/polyMesh/faces ]
then
    rm -r constant/polyMesh 2> /dev/null
    cp -r "$MESHDIR"/constant/polyMesh constant/polyMesh
elif [ ! -f constant/polyMesh/faces ]
then
    echo "Fatal error: Unable to find mesh in directory $MESHDIR" 1>&2
    exit 1
fi

# Detect available turbulence lib
if [ -f "$FOAM_LIBBIN/libmomentumTransportModels.so" ] || [ -f "$FOAM_LIBBIN/libmomentumTransportModels.dll" ]
then
    echo \"libmomentumTransportModels.so\" > system/turbulenceLib
else
    echo \"libturbulenceModels.so\" > system/turbulenceLib
fi

# Update patch name and type
runCommand createPatch -overwrite

# Scaling .stl files exported from FreeCAD from mm to m
if [ -z $FOAM_API ] && ( [ $WM_PROJECT_VERSION == "dev" ] || [ $WM_PROJECT_VERSION -ge 9 ] )
then
    runCommand surfaceTransformPoints "scale=(0.001 0.001 0.001)" "constant/triSurface/Cylinder.stl" "constant/triSurface/CylinderScaled.stl"
else
    runCommand surfaceTransformPoints -scale "(0.001 0.001 0.001)" "constant/triSurface/Cylinder.stl" "constant/triSurface/CylinderScaled.stl"
fi

# Set cell zones contained inside the .stl surfaces
runCommand topoSet -dict system/topoSetZonesDict

PNAME=p

# Parallel decomposition
runCommand decomposePar -force

# Mesh renumbering
runCommand mpiexec -np 4 renumberMesh -parallel -overwrite

# Initialise flow
# Baffle BC does not work with potentialFoam; do not initialise p
runCommand mpiexec -np 4 potentialFoam -parallel -initialiseUBCs -pName $PNAME

# Run application in parallel
runCommand mpiexec -np 4 porousSimpleFoam -parallel

