#!/bin/bash

runParallel()
{
    nproc="$1"
    shift
    exe="$(which $1)"
    sol=$(basename -- "$1")
    sol="${sol%.*}"
    shift
    if [ -f log."$sol" ]; then rm log."$sol"; fi
    export OMPI_MCA_btl_vader_single_copy_mechanism=none  # Workaround for open-mpi/docker bug
%{%(system/hostFileRequired%)
%:False
    mpiexec %(system/MPIOptionsOMPI%) -np $nproc "$exe" -parallel "$@" 1> >(tee -a log."$sol") 2> >(tee -a log."$sol" >&2)
%:True
    mpiexec %(system/MPIOptionsOMPI%) --hostfile %(system/hostFileName%) -np $nproc "$exe" -parallel "$@" 1> >(tee -a log."$sol") 2> >(tee -a log."$sol" >&2)
%}
    err=$?
    if [ ! $err -eq 0 ]; then exit $err; fi
}

runCommand()
{
    sol=$(basename -- "$1")
    sol="${sol%.*}"
    if [ -f log."$sol" ]; then rm log."$sol"; fi
    "$@" 1> >(tee -a log."$sol") 2> >(tee -a log."$sol" >&2)
    err=$?
    if [ ! $err -eq 0 ]; then exit $err; fi
}

# Unset and source bashrc
%{%(system/FoamRuntime%)
%:Posix
FOAMDIR="%(system/TranslatedFoamPath%)"
%:BashWSL
FOAMDIR="%(system/TranslatedFoamPath%)"
%}
if [ ! -z "$FOAMDIR" ]
then
    source "$FOAMDIR/etc/config.sh/unset" 2> /dev/null
    source "$FOAMDIR/etc/bashrc"
fi

# Copy mesh from mesh case dir if available
MESHDIR="%(meshDir%)"
if [ -f "$MESHDIR"/constant/polyMesh/faces ]
then
    rm -rf constant/polyMesh
    cp -r "$MESHDIR"/constant/polyMesh constant/polyMesh
elif [ ! -f constant/polyMesh/faces ]
then
    echo "Fatal error: Unable to find mesh in directory $MESHDIR" 1>&2
    exit 1
fi

# Detect available turbulence lib
if [ -f "$FOAM_LIBBIN/libmomentumTransportModels.so" ] || [ -f "$FOAM_LIBBIN/libmomentumTransportModels.dll" ]
then
    echo \"libmomentumTransportModels.so\" > system/turbulenceLib
else
    echo \"libturbulenceModels.so\" > system/turbulenceLib
fi

# Change specification of interface compression in OF 13+
if [ -z ${FOAM_API+x} ] && [ "$WM_PROJECT_VERSION" -ge 13 ]
then
    echo "div(phi,alpha) Gauss interfaceCompression vanLeer 1;" > system/alphaDivScheme
    echo "" > system/cAlpha
else
    echo "div(phi,alpha) Gauss vanLeer;" > system/alphaDivScheme
    echo "cAlpha 1;" > system/cAlpha
fi

%{%(dynamicMeshEnabled%)
%:True
mkdir -p 0/include
if [ -z ${FOAM_API+x} ] && [ "$WM_PROJECT_VERSION" -ge 9 ]
then
    echo "type internal;" | tee 0/include/helperPatchFieldType system/helperPatchType
else
    echo "type fixedValue;" > 0/include/helperPatchFieldType
    echo "type patch;" > system/helperPatchType
fi

%}
%{%(createPatchesForPeriodics%)
%:True
mkdir -p 0/MMR
which createNonConformalCouples > /dev/null 2>&1
if [ $? == 0 ]
then
	echo "type wall;" > system/periodic_type

    echo "type movingWallSlipVelocity;" > 0/MMR/vector
    echo "value \$internalField;" >> 0/MMR/vector

    echo "type zeroGradient;" > 0/MMR/scalar

    echo "type calculated;" > 0/MMR/calculated
    echo "value uniform 0;" >> 0/MMR/calculated
else
	echo "type cyclicAMI;" | tee 0/MMR/{scalar,vector,calculated} system/periodic_type
	echo "value \$internalField;" | tee -a 0/MMR/{scalar,vector,calculated}
fi

%:False
%{%(MovingMeshRegionsPresent%)
%:True
mkdir -p 0/MMR
which createNonConformalCouples > /dev/null 2>&1
if [ $? == 0 ]
then
    echo "type movingWallSlipVelocity;" > 0/MMR/vector
    echo "value \$internalField;" >> 0/MMR/vector

    echo "type zeroGradient;" > 0/MMR/scalar

    echo "type calculated;" > 0/MMR/calculated
    echo "value uniform 0;" >> 0/MMR/calculated
else
	echo "type cyclicAMI;" | tee 0/MMR/{scalar,vector,calculated}
	echo "value \$internalField;" | tee -a 0/MMR/{scalar,vector,calculated}
fi

%}
%}
%{%(scalarTransportFunctionsEnabled%)
%:True
# Enable fvOption source for scalar transport in OpenFOAM v10+
if [ -z ${FOAM_API+x} ] && [ "$WM_PROJECT_VERSION" -ge 10 ]
then
    cp system/fvOptionsScalarTransport_OF10 system/fvOptionsScalarTransport
fi

%}
%{%(physics/TurbulenceModel%)
%:kOmegaSSTDES kOmegaSSTDDES kOmegaSSTIDDES SpalartAllmarasDES SpalartAllmarasDDES SpalartAllmarasIDDES
# write the type of the DESModelRegions function for of10+ and for others
if [ "$WM_PROJECT_VERSION" -ge 10 ] && [ "${WM_PROJECT_VERSION:0:1}" != "v" ]
then
       echo "type                      writeObjects; // of10" > system/DESModelRegionsFunction
       echo "libs                      (\"libutilityFunctionObjects.so\"); //of10" >> system/DESModelRegionsFunction
else
       echo "type            DESModelRegions;" > system/DESModelRegionsFunction
       echo "libs            (\"libfieldFunctionObjects.so\");" >> system/DESModelRegionsFunction
fi

%}
# Update patch name and type
runCommand createPatch -overwrite

%{%(createPatchesForPeriodics%)
%:True
which createNonConformalCouples > /dev/null 2>&1
if [ $? == 0 ]
then
%{%(createPeriodics%)
%{%(createPeriodics/%(0%)/PeriodicMaster%)
%:True
	runCommand createNonConformalCouples -overwrite %(0%)_master %(0%)_slave
	mv log.createNonConformalCouples log.createNonConformalCouples.%(0%)
%}
%}
fi

%}
%{%(zonesPresent%)
%:True
# Set cell zones contained inside the .stl surfaces
which createZones > /dev/null 2>&1
if [ $? == 0 ]
then
	runCommand createZones -dict system/createZonesDict
else
	runCommand topoSet -dict system/topoSetZonesDict
fi

%}
%{%(multiRegionEnabled%)
%:True
# Split the combined mesh into its fluid and solid regions
runCommand splitMeshRegions -cellZonesOnly -overwrite

%{%(meanVelocityForceCellZonesPresent%)
%:True
# Create mean velocity force cell zones inside the fluid region mesh
runCommand topoSet -region %(multiRegionFluidNames/0%) -dict "$PWD/system/%(multiRegionFluidNames/0%)/topoSetMeanVelocityForceZonesDict"

%}
# Complete the interface patch and field setup created by splitMeshRegions
env -u PYTHONPATH -u PYTHONHOME python3 prepareMultiRegion.py
status=$?
if [ ! $status -eq 0 ]; then exit $status; fi

%}
%{%(initialisationZonesPresent%)
%:True
# Set internal fields according to setFieldsDict
# use the OF13 dict for setFields if using openfoam 13 and later
if [ "$WM_PROJECT_VERSION" -ge 13 ] && [ "${WM_PROJECT_VERSION:0:1}" != "v" ]
then
	runCommand setFields -dict system/setFieldsDict_OF13
else
	runCommand setFields
fi

%}
%{%(bafflesPresent%)
%:True
%{%(createPatchesFromSnappyBaffles%)
%:False
# Combine mesh faceZones
runCommand topoSet -dict system/topoSetBafflesDict

# Creating baffles
runCommand createBaffles -overwrite

%}
%}
%{%(runChangeDictionary%)
%:True
# Update patch name and type
runCommand changeDictionary

%}
%{%(initialValues/PotentialFlow%)
%:True
%{%(solver/SolverName%)
%:buoyantSimpleFoam buoyantPimpleFoam interFoam multiphaseInterFoam
PNAME=p_rgh
%:default
PNAME=p
%}

%}
%{%(solver/Parallel%)
%:True
%{%(multiRegionEnabled%)
%:True
# Parallel decomposition for all CHT regions
for region in $(ls -d constant/*/polyMesh 2>/dev/null | cut -d/ -f2); do
    mkdir -p system/$region
    cp system/decomposeParDict system/$region/decomposeParDict
done
runCommand decomposePar -allRegions -force
%:False
# Parallel decomposition
if [ ! -d processor0 ]
then
    runCommand decomposePar -force
fi
%}

# Pick up number of parallel processes
NPROC=$(foamDictionary -entry "numberOfSubdomains" -value system/decomposeParDict)

%{%(dynamicMeshEnabled%)
%:False
%{%(multiRegionEnabled%)
%:False
%{%(createPatchesForPeriodics%)
%:False
%{%(MovingMeshRegionsPresent%)
%:False
# Mesh renumbering
runParallel $NPROC renumberMesh -overwrite
%}
%}
%}
%:True
# Mesh renumbering does not work in Foundation with dynamic mesh
%}

%{%(createPatchesForPeriodics%)
%:True
which createNonConformalCouples > /dev/null 2>&1
if [ $? == 0 ]
then
%{%(createPeriodics%)
%{%(createPeriodics/%(0%)/PeriodicMaster%)
%:True
	runParallel $NPROC createNonConformalCouples -overwrite %(0%)_master %(0%)_slave
	mv log.createNonConformalCouples log.createNonConformalCouples.%(0%)
%}
%}
fi

%}
%{%(initialValues/PotentialFlow%)
%:True
%{%(multiRegionEnabled%)
%:False
# Initialise flow
%{%(bafflesPresent%)
%:True
# Baffle BC does not work with potentialFoam; do not initialise p
runParallel $NPROC potentialFoam -initialiseUBCs -pName $PNAME
%:default
%{%(initialValues/PotentialFlowP%)
%:True
runParallel $NPROC potentialFoam -initialiseUBCs -pName $PNAME -writep
%:default
runParallel $NPROC potentialFoam -initialiseUBCs -pName $PNAME
%}
%}
%{%(solver/SolverName%)
%:buoyantSimpleFoam buoyantPimpleFoam interFoam multiphaseInterFoam
# Remove phi with wrong units
rm -f processor*/0/phi
%}
%}

%}
# Run application in parallel
# Detect new foamRun in Foundation versions >= 11 and translate solver
which foamRun > /dev/null 2>&1
if [ $? == 0 ]
then
%{%(solver/SolverName%)
%:simpleFoam pimpleFoam
    runParallel $NPROC foamRun -solver incompressibleFluid
%:buoyantSimpleFoam buoyantPimpleFoam
    runParallel $NPROC foamRun -solver fluid
%:interFoam
    runParallel $NPROC foamRun -solver incompressibleVoF
%:multiphaseInterFoam
    runParallel $NPROC foamRun -solver incompressibleMultiphaseVoF
%:chtMultiRegionSimpleFoam
    if command -v chtMultiRegionSimpleFoam > /dev/null 2>&1
    then
        runParallel $NPROC chtMultiRegionSimpleFoam
    else
        runParallel $NPROC chtMultiRegionFoam
    fi
%:chtMultiRegionFoam
    runParallel $NPROC chtMultiRegionFoam
%:default
    runParallel $NPROC %(solver/SolverName%)
%}
else
    runParallel $NPROC %(solver/SolverName%)
fi
%:False
%{%(dynamicMeshEnabled%)
%:False
%{%(multiRegionEnabled%)
%:False
%{%(createPatchesForPeriodics%)
%:False
%{%(MovingMeshRegionsPresent%)
%:False
# Mesh renumbering
runCommand renumberMesh -overwrite
%}
%}
%}
%:True
# Mesh renumbering does not currently work in Foundation with dynamic mesh
# runCommand renumberMesh -overwrite
%}

%{%(initialValues/PotentialFlow%)
%:True
%{%(multiRegionEnabled%)
%:False
# Initialise flow
%{%(bafflesPresent%)
%:True
# Baffle BC does not work with potentialFoam; do not initialise p
runCommand potentialFoam -initialiseUBCs -pName $PNAME
%:default
%{%(initialValues/PotentialFlowP%)
%:True
runCommand potentialFoam -initialiseUBCs -pName $PNAME -writep
%:default
runCommand potentialFoam -initialiseUBCs -pName $PNAME
%}
%}
%{%(solver/SolverName%)
%:buoyantSimpleFoam buoyantPimpleFoam interFoam multiphaseInterFoam
# Remove phi with wrong units
rm -f 0/phi
%}
%}

%}
# Run application
# Detect new foamRun in Foundation versions >= 11 and translate solver
which foamRun > /dev/null 2>&1
if [ $? == 0 ]
then
%{%(solver/SolverName%)
%:simpleFoam pimpleFoam
    runCommand foamRun -solver incompressibleFluid
%:buoyantSimpleFoam buoyantPimpleFoam
    runCommand foamRun -solver fluid
%:interFoam
    runCommand foamRun -solver incompressibleVoF
%:multiphaseInterFoam
    runCommand foamRun -solver incompressibleMultiphaseVoF
%:chtMultiRegionSimpleFoam
    if command -v chtMultiRegionSimpleFoam > /dev/null 2>&1
    then
        runCommand chtMultiRegionSimpleFoam
    else
        runCommand chtMultiRegionFoam
    fi
%:chtMultiRegionFoam
    runCommand chtMultiRegionFoam
%:default
    runCommand %(solver/SolverName%)
%}
else
    runCommand %(solver/SolverName%)
fi
%}
